// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather_forecast.proto

package mwo.psr.proto;

public final class WeatherForecastProtos {
  private WeatherForecastProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DailyForecastOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.DailyForecast)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     * @return The date.
     */
    com.google.protobuf.Timestamp getDate();
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast> 
        getCityForecastsList();
    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast getCityForecasts(int index);
    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    int getCityForecastsCount();
    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    java.util.List<? extends mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder> 
        getCityForecastsOrBuilderList();
    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder getCityForecastsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.DailyForecast}
   */
  public static final class DailyForecast extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.DailyForecast)
      DailyForecastOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DailyForecast.newBuilder() to construct.
    private DailyForecast(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DailyForecast() {
      cityForecasts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DailyForecast();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mwo.psr.proto.WeatherForecastProtos.DailyForecast.class, mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder.class);
    }

    public interface CityForecastOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tutorial.DailyForecast.CityForecast)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string city_name = 1;</code>
       * @return The cityName.
       */
      java.lang.String getCityName();
      /**
       * <code>string city_name = 1;</code>
       * @return The bytes for cityName.
       */
      com.google.protobuf.ByteString
          getCityNameBytes();

      /**
       * <code>float temperature = 2;</code>
       * @return The temperature.
       */
      float getTemperature();

      /**
       * <code>float humidity = 3;</code>
       * @return The humidity.
       */
      float getHumidity();

      /**
       * <code>float cloudiness = 4;</code>
       * @return The cloudiness.
       */
      float getCloudiness();

      /**
       * <code>float pressure = 5;</code>
       * @return The pressure.
       */
      float getPressure();
    }
    /**
     * Protobuf type {@code tutorial.DailyForecast.CityForecast}
     */
    public static final class CityForecast extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tutorial.DailyForecast.CityForecast)
        CityForecastOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use CityForecast.newBuilder() to construct.
      private CityForecast(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CityForecast() {
        cityName_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new CityForecast();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_CityForecast_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_CityForecast_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.class, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder.class);
      }

      public static final int CITY_NAME_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object cityName_ = "";
      /**
       * <code>string city_name = 1;</code>
       * @return The cityName.
       */
      @java.lang.Override
      public java.lang.String getCityName() {
        java.lang.Object ref = cityName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cityName_ = s;
          return s;
        }
      }
      /**
       * <code>string city_name = 1;</code>
       * @return The bytes for cityName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCityNameBytes() {
        java.lang.Object ref = cityName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cityName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TEMPERATURE_FIELD_NUMBER = 2;
      private float temperature_ = 0F;
      /**
       * <code>float temperature = 2;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public float getTemperature() {
        return temperature_;
      }

      public static final int HUMIDITY_FIELD_NUMBER = 3;
      private float humidity_ = 0F;
      /**
       * <code>float humidity = 3;</code>
       * @return The humidity.
       */
      @java.lang.Override
      public float getHumidity() {
        return humidity_;
      }

      public static final int CLOUDINESS_FIELD_NUMBER = 4;
      private float cloudiness_ = 0F;
      /**
       * <code>float cloudiness = 4;</code>
       * @return The cloudiness.
       */
      @java.lang.Override
      public float getCloudiness() {
        return cloudiness_;
      }

      public static final int PRESSURE_FIELD_NUMBER = 5;
      private float pressure_ = 0F;
      /**
       * <code>float pressure = 5;</code>
       * @return The pressure.
       */
      @java.lang.Override
      public float getPressure() {
        return pressure_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cityName_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cityName_);
        }
        if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
          output.writeFloat(2, temperature_);
        }
        if (java.lang.Float.floatToRawIntBits(humidity_) != 0) {
          output.writeFloat(3, humidity_);
        }
        if (java.lang.Float.floatToRawIntBits(cloudiness_) != 0) {
          output.writeFloat(4, cloudiness_);
        }
        if (java.lang.Float.floatToRawIntBits(pressure_) != 0) {
          output.writeFloat(5, pressure_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cityName_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cityName_);
        }
        if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, temperature_);
        }
        if (java.lang.Float.floatToRawIntBits(humidity_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, humidity_);
        }
        if (java.lang.Float.floatToRawIntBits(cloudiness_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(4, cloudiness_);
        }
        if (java.lang.Float.floatToRawIntBits(pressure_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(5, pressure_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast)) {
          return super.equals(obj);
        }
        mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast other = (mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast) obj;

        if (!getCityName()
            .equals(other.getCityName())) return false;
        if (java.lang.Float.floatToIntBits(getTemperature())
            != java.lang.Float.floatToIntBits(
                other.getTemperature())) return false;
        if (java.lang.Float.floatToIntBits(getHumidity())
            != java.lang.Float.floatToIntBits(
                other.getHumidity())) return false;
        if (java.lang.Float.floatToIntBits(getCloudiness())
            != java.lang.Float.floatToIntBits(
                other.getCloudiness())) return false;
        if (java.lang.Float.floatToIntBits(getPressure())
            != java.lang.Float.floatToIntBits(
                other.getPressure())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CITY_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getCityName().hashCode();
        hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getTemperature());
        hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getHumidity());
        hash = (37 * hash) + CLOUDINESS_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getCloudiness());
        hash = (37 * hash) + PRESSURE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPressure());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tutorial.DailyForecast.CityForecast}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:tutorial.DailyForecast.CityForecast)
          mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_CityForecast_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_CityForecast_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.class, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder.class);
        }

        // Construct using mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          cityName_ = "";
          temperature_ = 0F;
          humidity_ = 0F;
          cloudiness_ = 0F;
          pressure_ = 0F;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_CityForecast_descriptor;
        }

        @java.lang.Override
        public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast getDefaultInstanceForType() {
          return mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.getDefaultInstance();
        }

        @java.lang.Override
        public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast build() {
          mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast buildPartial() {
          mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast result = new mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.cityName_ = cityName_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.temperature_ = temperature_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.humidity_ = humidity_;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.cloudiness_ = cloudiness_;
          }
          if (((from_bitField0_ & 0x00000010) != 0)) {
            result.pressure_ = pressure_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast) {
            return mergeFrom((mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast other) {
          if (other == mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.getDefaultInstance()) return this;
          if (!other.getCityName().isEmpty()) {
            cityName_ = other.cityName_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (other.getTemperature() != 0F) {
            setTemperature(other.getTemperature());
          }
          if (other.getHumidity() != 0F) {
            setHumidity(other.getHumidity());
          }
          if (other.getCloudiness() != 0F) {
            setCloudiness(other.getCloudiness());
          }
          if (other.getPressure() != 0F) {
            setPressure(other.getPressure());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  cityName_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 21: {
                  temperature_ = input.readFloat();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 21
                case 29: {
                  humidity_ = input.readFloat();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 29
                case 37: {
                  cloudiness_ = input.readFloat();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 37
                case 45: {
                  pressure_ = input.readFloat();
                  bitField0_ |= 0x00000010;
                  break;
                } // case 45
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object cityName_ = "";
        /**
         * <code>string city_name = 1;</code>
         * @return The cityName.
         */
        public java.lang.String getCityName() {
          java.lang.Object ref = cityName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            cityName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string city_name = 1;</code>
         * @return The bytes for cityName.
         */
        public com.google.protobuf.ByteString
            getCityNameBytes() {
          java.lang.Object ref = cityName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            cityName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string city_name = 1;</code>
         * @param value The cityName to set.
         * @return This builder for chaining.
         */
        public Builder setCityName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          cityName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string city_name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCityName() {
          cityName_ = getDefaultInstance().getCityName();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string city_name = 1;</code>
         * @param value The bytes for cityName to set.
         * @return This builder for chaining.
         */
        public Builder setCityNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          cityName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private float temperature_ ;
        /**
         * <code>float temperature = 2;</code>
         * @return The temperature.
         */
        @java.lang.Override
        public float getTemperature() {
          return temperature_;
        }
        /**
         * <code>float temperature = 2;</code>
         * @param value The temperature to set.
         * @return This builder for chaining.
         */
        public Builder setTemperature(float value) {

          temperature_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>float temperature = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearTemperature() {
          bitField0_ = (bitField0_ & ~0x00000002);
          temperature_ = 0F;
          onChanged();
          return this;
        }

        private float humidity_ ;
        /**
         * <code>float humidity = 3;</code>
         * @return The humidity.
         */
        @java.lang.Override
        public float getHumidity() {
          return humidity_;
        }
        /**
         * <code>float humidity = 3;</code>
         * @param value The humidity to set.
         * @return This builder for chaining.
         */
        public Builder setHumidity(float value) {

          humidity_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>float humidity = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearHumidity() {
          bitField0_ = (bitField0_ & ~0x00000004);
          humidity_ = 0F;
          onChanged();
          return this;
        }

        private float cloudiness_ ;
        /**
         * <code>float cloudiness = 4;</code>
         * @return The cloudiness.
         */
        @java.lang.Override
        public float getCloudiness() {
          return cloudiness_;
        }
        /**
         * <code>float cloudiness = 4;</code>
         * @param value The cloudiness to set.
         * @return This builder for chaining.
         */
        public Builder setCloudiness(float value) {

          cloudiness_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>float cloudiness = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearCloudiness() {
          bitField0_ = (bitField0_ & ~0x00000008);
          cloudiness_ = 0F;
          onChanged();
          return this;
        }

        private float pressure_ ;
        /**
         * <code>float pressure = 5;</code>
         * @return The pressure.
         */
        @java.lang.Override
        public float getPressure() {
          return pressure_;
        }
        /**
         * <code>float pressure = 5;</code>
         * @param value The pressure to set.
         * @return This builder for chaining.
         */
        public Builder setPressure(float value) {

          pressure_ = value;
          bitField0_ |= 0x00000010;
          onChanged();
          return this;
        }
        /**
         * <code>float pressure = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearPressure() {
          bitField0_ = (bitField0_ & ~0x00000010);
          pressure_ = 0F;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tutorial.DailyForecast.CityForecast)
      }

      // @@protoc_insertion_point(class_scope:tutorial.DailyForecast.CityForecast)
      private static final mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast();
      }

      public static mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CityForecast>
          PARSER = new com.google.protobuf.AbstractParser<CityForecast>() {
        @java.lang.Override
        public CityForecast parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<CityForecast> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<CityForecast> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DATE_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp date_;
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     * @return Whether the date field is set.
     */
    @java.lang.Override
    public boolean hasDate() {
      return date_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     * @return The date.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDate() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }

    public static final int CITY_FORECASTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast> cityForecasts_;
    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    @java.lang.Override
    public java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast> getCityForecastsList() {
      return cityForecasts_;
    }
    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder> 
        getCityForecastsOrBuilderList() {
      return cityForecasts_;
    }
    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    @java.lang.Override
    public int getCityForecastsCount() {
      return cityForecasts_.size();
    }
    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    @java.lang.Override
    public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast getCityForecasts(int index) {
      return cityForecasts_.get(index);
    }
    /**
     * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
     */
    @java.lang.Override
    public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder getCityForecastsOrBuilder(
        int index) {
      return cityForecasts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (date_ != null) {
        output.writeMessage(1, getDate());
      }
      for (int i = 0; i < cityForecasts_.size(); i++) {
        output.writeMessage(2, cityForecasts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (date_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDate());
      }
      for (int i = 0; i < cityForecasts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, cityForecasts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mwo.psr.proto.WeatherForecastProtos.DailyForecast)) {
        return super.equals(obj);
      }
      mwo.psr.proto.WeatherForecastProtos.DailyForecast other = (mwo.psr.proto.WeatherForecastProtos.DailyForecast) obj;

      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (!getCityForecastsList()
          .equals(other.getCityForecastsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      if (getCityForecastsCount() > 0) {
        hash = (37 * hash) + CITY_FORECASTS_FIELD_NUMBER;
        hash = (53 * hash) + getCityForecastsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mwo.psr.proto.WeatherForecastProtos.DailyForecast prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.DailyForecast}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.DailyForecast)
        mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mwo.psr.proto.WeatherForecastProtos.DailyForecast.class, mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder.class);
      }

      // Construct using mwo.psr.proto.WeatherForecastProtos.DailyForecast.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        date_ = null;
        if (dateBuilder_ != null) {
          dateBuilder_.dispose();
          dateBuilder_ = null;
        }
        if (cityForecastsBuilder_ == null) {
          cityForecasts_ = java.util.Collections.emptyList();
        } else {
          cityForecasts_ = null;
          cityForecastsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_DailyForecast_descriptor;
      }

      @java.lang.Override
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast getDefaultInstanceForType() {
        return mwo.psr.proto.WeatherForecastProtos.DailyForecast.getDefaultInstance();
      }

      @java.lang.Override
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast build() {
        mwo.psr.proto.WeatherForecastProtos.DailyForecast result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast buildPartial() {
        mwo.psr.proto.WeatherForecastProtos.DailyForecast result = new mwo.psr.proto.WeatherForecastProtos.DailyForecast(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(mwo.psr.proto.WeatherForecastProtos.DailyForecast result) {
        if (cityForecastsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            cityForecasts_ = java.util.Collections.unmodifiableList(cityForecasts_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.cityForecasts_ = cityForecasts_;
        } else {
          result.cityForecasts_ = cityForecastsBuilder_.build();
        }
      }

      private void buildPartial0(mwo.psr.proto.WeatherForecastProtos.DailyForecast result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.date_ = dateBuilder_ == null
              ? date_
              : dateBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mwo.psr.proto.WeatherForecastProtos.DailyForecast) {
          return mergeFrom((mwo.psr.proto.WeatherForecastProtos.DailyForecast)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mwo.psr.proto.WeatherForecastProtos.DailyForecast other) {
        if (other == mwo.psr.proto.WeatherForecastProtos.DailyForecast.getDefaultInstance()) return this;
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        if (cityForecastsBuilder_ == null) {
          if (!other.cityForecasts_.isEmpty()) {
            if (cityForecasts_.isEmpty()) {
              cityForecasts_ = other.cityForecasts_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCityForecastsIsMutable();
              cityForecasts_.addAll(other.cityForecasts_);
            }
            onChanged();
          }
        } else {
          if (!other.cityForecasts_.isEmpty()) {
            if (cityForecastsBuilder_.isEmpty()) {
              cityForecastsBuilder_.dispose();
              cityForecastsBuilder_ = null;
              cityForecasts_ = other.cityForecasts_;
              bitField0_ = (bitField0_ & ~0x00000002);
              cityForecastsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCityForecastsFieldBuilder() : null;
            } else {
              cityForecastsBuilder_.addAllMessages(other.cityForecasts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getDateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast m =
                    input.readMessage(
                        mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.parser(),
                        extensionRegistry);
                if (cityForecastsBuilder_ == null) {
                  ensureCityForecastsIsMutable();
                  cityForecasts_.add(m);
                } else {
                  cityForecastsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp date_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp date = 1;</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp date = 1;</code>
       * @return The date.
       */
      public com.google.protobuf.Timestamp getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 1;</code>
       */
      public Builder setDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
        } else {
          dateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 1;</code>
       */
      public Builder setDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 1;</code>
       */
      public Builder mergeDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            date_ != null &&
            date_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getDateBuilder().mergeFrom(value);
          } else {
            date_ = value;
          }
        } else {
          dateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 1;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = null;
        if (dateBuilder_ != null) {
          dateBuilder_.dispose();
          dateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp date = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }

      private java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast> cityForecasts_ =
        java.util.Collections.emptyList();
      private void ensureCityForecastsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          cityForecasts_ = new java.util.ArrayList<mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast>(cityForecasts_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder> cityForecastsBuilder_;

      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast> getCityForecastsList() {
        if (cityForecastsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cityForecasts_);
        } else {
          return cityForecastsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public int getCityForecastsCount() {
        if (cityForecastsBuilder_ == null) {
          return cityForecasts_.size();
        } else {
          return cityForecastsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast getCityForecasts(int index) {
        if (cityForecastsBuilder_ == null) {
          return cityForecasts_.get(index);
        } else {
          return cityForecastsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public Builder setCityForecasts(
          int index, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast value) {
        if (cityForecastsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCityForecastsIsMutable();
          cityForecasts_.set(index, value);
          onChanged();
        } else {
          cityForecastsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public Builder setCityForecasts(
          int index, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder builderForValue) {
        if (cityForecastsBuilder_ == null) {
          ensureCityForecastsIsMutable();
          cityForecasts_.set(index, builderForValue.build());
          onChanged();
        } else {
          cityForecastsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public Builder addCityForecasts(mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast value) {
        if (cityForecastsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCityForecastsIsMutable();
          cityForecasts_.add(value);
          onChanged();
        } else {
          cityForecastsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public Builder addCityForecasts(
          int index, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast value) {
        if (cityForecastsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCityForecastsIsMutable();
          cityForecasts_.add(index, value);
          onChanged();
        } else {
          cityForecastsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public Builder addCityForecasts(
          mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder builderForValue) {
        if (cityForecastsBuilder_ == null) {
          ensureCityForecastsIsMutable();
          cityForecasts_.add(builderForValue.build());
          onChanged();
        } else {
          cityForecastsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public Builder addCityForecasts(
          int index, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder builderForValue) {
        if (cityForecastsBuilder_ == null) {
          ensureCityForecastsIsMutable();
          cityForecasts_.add(index, builderForValue.build());
          onChanged();
        } else {
          cityForecastsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public Builder addAllCityForecasts(
          java.lang.Iterable<? extends mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast> values) {
        if (cityForecastsBuilder_ == null) {
          ensureCityForecastsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cityForecasts_);
          onChanged();
        } else {
          cityForecastsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public Builder clearCityForecasts() {
        if (cityForecastsBuilder_ == null) {
          cityForecasts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          cityForecastsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public Builder removeCityForecasts(int index) {
        if (cityForecastsBuilder_ == null) {
          ensureCityForecastsIsMutable();
          cityForecasts_.remove(index);
          onChanged();
        } else {
          cityForecastsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder getCityForecastsBuilder(
          int index) {
        return getCityForecastsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder getCityForecastsOrBuilder(
          int index) {
        if (cityForecastsBuilder_ == null) {
          return cityForecasts_.get(index);  } else {
          return cityForecastsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public java.util.List<? extends mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder> 
           getCityForecastsOrBuilderList() {
        if (cityForecastsBuilder_ != null) {
          return cityForecastsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cityForecasts_);
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder addCityForecastsBuilder() {
        return getCityForecastsFieldBuilder().addBuilder(
            mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder addCityForecastsBuilder(
          int index) {
        return getCityForecastsFieldBuilder().addBuilder(
            index, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.DailyForecast.CityForecast city_forecasts = 2;</code>
       */
      public java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder> 
           getCityForecastsBuilderList() {
        return getCityForecastsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder> 
          getCityForecastsFieldBuilder() {
        if (cityForecastsBuilder_ == null) {
          cityForecastsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecast.Builder, mwo.psr.proto.WeatherForecastProtos.DailyForecast.CityForecastOrBuilder>(
                  cityForecasts_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          cityForecasts_ = null;
        }
        return cityForecastsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.DailyForecast)
    }

    // @@protoc_insertion_point(class_scope:tutorial.DailyForecast)
    private static final mwo.psr.proto.WeatherForecastProtos.DailyForecast DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mwo.psr.proto.WeatherForecastProtos.DailyForecast();
    }

    public static mwo.psr.proto.WeatherForecastProtos.DailyForecast getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DailyForecast>
        PARSER = new com.google.protobuf.AbstractParser<DailyForecast>() {
      @java.lang.Override
      public DailyForecast parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DailyForecast> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DailyForecast> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mwo.psr.proto.WeatherForecastProtos.DailyForecast getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WeatherForecastOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.WeatherForecast)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast> 
        getDailyForecastsList();
    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    mwo.psr.proto.WeatherForecastProtos.DailyForecast getDailyForecasts(int index);
    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    int getDailyForecastsCount();
    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    java.util.List<? extends mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder> 
        getDailyForecastsOrBuilderList();
    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder getDailyForecastsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.WeatherForecast}
   */
  public static final class WeatherForecast extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.WeatherForecast)
      WeatherForecastOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WeatherForecast.newBuilder() to construct.
    private WeatherForecast(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WeatherForecast() {
      dailyForecasts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WeatherForecast();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_WeatherForecast_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_WeatherForecast_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mwo.psr.proto.WeatherForecastProtos.WeatherForecast.class, mwo.psr.proto.WeatherForecastProtos.WeatherForecast.Builder.class);
    }

    public static final int DAILY_FORECASTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast> dailyForecasts_;
    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast> getDailyForecastsList() {
      return dailyForecasts_;
    }
    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder> 
        getDailyForecastsOrBuilderList() {
      return dailyForecasts_;
    }
    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    @java.lang.Override
    public int getDailyForecastsCount() {
      return dailyForecasts_.size();
    }
    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    @java.lang.Override
    public mwo.psr.proto.WeatherForecastProtos.DailyForecast getDailyForecasts(int index) {
      return dailyForecasts_.get(index);
    }
    /**
     * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
     */
    @java.lang.Override
    public mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder getDailyForecastsOrBuilder(
        int index) {
      return dailyForecasts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dailyForecasts_.size(); i++) {
        output.writeMessage(1, dailyForecasts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dailyForecasts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dailyForecasts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mwo.psr.proto.WeatherForecastProtos.WeatherForecast)) {
        return super.equals(obj);
      }
      mwo.psr.proto.WeatherForecastProtos.WeatherForecast other = (mwo.psr.proto.WeatherForecastProtos.WeatherForecast) obj;

      if (!getDailyForecastsList()
          .equals(other.getDailyForecastsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDailyForecastsCount() > 0) {
        hash = (37 * hash) + DAILY_FORECASTS_FIELD_NUMBER;
        hash = (53 * hash) + getDailyForecastsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mwo.psr.proto.WeatherForecastProtos.WeatherForecast prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.WeatherForecast}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.WeatherForecast)
        mwo.psr.proto.WeatherForecastProtos.WeatherForecastOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_WeatherForecast_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_WeatherForecast_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mwo.psr.proto.WeatherForecastProtos.WeatherForecast.class, mwo.psr.proto.WeatherForecastProtos.WeatherForecast.Builder.class);
      }

      // Construct using mwo.psr.proto.WeatherForecastProtos.WeatherForecast.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (dailyForecastsBuilder_ == null) {
          dailyForecasts_ = java.util.Collections.emptyList();
        } else {
          dailyForecasts_ = null;
          dailyForecastsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mwo.psr.proto.WeatherForecastProtos.internal_static_tutorial_WeatherForecast_descriptor;
      }

      @java.lang.Override
      public mwo.psr.proto.WeatherForecastProtos.WeatherForecast getDefaultInstanceForType() {
        return mwo.psr.proto.WeatherForecastProtos.WeatherForecast.getDefaultInstance();
      }

      @java.lang.Override
      public mwo.psr.proto.WeatherForecastProtos.WeatherForecast build() {
        mwo.psr.proto.WeatherForecastProtos.WeatherForecast result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mwo.psr.proto.WeatherForecastProtos.WeatherForecast buildPartial() {
        mwo.psr.proto.WeatherForecastProtos.WeatherForecast result = new mwo.psr.proto.WeatherForecastProtos.WeatherForecast(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(mwo.psr.proto.WeatherForecastProtos.WeatherForecast result) {
        if (dailyForecastsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            dailyForecasts_ = java.util.Collections.unmodifiableList(dailyForecasts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dailyForecasts_ = dailyForecasts_;
        } else {
          result.dailyForecasts_ = dailyForecastsBuilder_.build();
        }
      }

      private void buildPartial0(mwo.psr.proto.WeatherForecastProtos.WeatherForecast result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mwo.psr.proto.WeatherForecastProtos.WeatherForecast) {
          return mergeFrom((mwo.psr.proto.WeatherForecastProtos.WeatherForecast)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mwo.psr.proto.WeatherForecastProtos.WeatherForecast other) {
        if (other == mwo.psr.proto.WeatherForecastProtos.WeatherForecast.getDefaultInstance()) return this;
        if (dailyForecastsBuilder_ == null) {
          if (!other.dailyForecasts_.isEmpty()) {
            if (dailyForecasts_.isEmpty()) {
              dailyForecasts_ = other.dailyForecasts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDailyForecastsIsMutable();
              dailyForecasts_.addAll(other.dailyForecasts_);
            }
            onChanged();
          }
        } else {
          if (!other.dailyForecasts_.isEmpty()) {
            if (dailyForecastsBuilder_.isEmpty()) {
              dailyForecastsBuilder_.dispose();
              dailyForecastsBuilder_ = null;
              dailyForecasts_ = other.dailyForecasts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dailyForecastsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDailyForecastsFieldBuilder() : null;
            } else {
              dailyForecastsBuilder_.addAllMessages(other.dailyForecasts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                mwo.psr.proto.WeatherForecastProtos.DailyForecast m =
                    input.readMessage(
                        mwo.psr.proto.WeatherForecastProtos.DailyForecast.parser(),
                        extensionRegistry);
                if (dailyForecastsBuilder_ == null) {
                  ensureDailyForecastsIsMutable();
                  dailyForecasts_.add(m);
                } else {
                  dailyForecastsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast> dailyForecasts_ =
        java.util.Collections.emptyList();
      private void ensureDailyForecastsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          dailyForecasts_ = new java.util.ArrayList<mwo.psr.proto.WeatherForecastProtos.DailyForecast>(dailyForecasts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          mwo.psr.proto.WeatherForecastProtos.DailyForecast, mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder, mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder> dailyForecastsBuilder_;

      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast> getDailyForecastsList() {
        if (dailyForecastsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dailyForecasts_);
        } else {
          return dailyForecastsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public int getDailyForecastsCount() {
        if (dailyForecastsBuilder_ == null) {
          return dailyForecasts_.size();
        } else {
          return dailyForecastsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast getDailyForecasts(int index) {
        if (dailyForecastsBuilder_ == null) {
          return dailyForecasts_.get(index);
        } else {
          return dailyForecastsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public Builder setDailyForecasts(
          int index, mwo.psr.proto.WeatherForecastProtos.DailyForecast value) {
        if (dailyForecastsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDailyForecastsIsMutable();
          dailyForecasts_.set(index, value);
          onChanged();
        } else {
          dailyForecastsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public Builder setDailyForecasts(
          int index, mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder builderForValue) {
        if (dailyForecastsBuilder_ == null) {
          ensureDailyForecastsIsMutable();
          dailyForecasts_.set(index, builderForValue.build());
          onChanged();
        } else {
          dailyForecastsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public Builder addDailyForecasts(mwo.psr.proto.WeatherForecastProtos.DailyForecast value) {
        if (dailyForecastsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDailyForecastsIsMutable();
          dailyForecasts_.add(value);
          onChanged();
        } else {
          dailyForecastsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public Builder addDailyForecasts(
          int index, mwo.psr.proto.WeatherForecastProtos.DailyForecast value) {
        if (dailyForecastsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDailyForecastsIsMutable();
          dailyForecasts_.add(index, value);
          onChanged();
        } else {
          dailyForecastsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public Builder addDailyForecasts(
          mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder builderForValue) {
        if (dailyForecastsBuilder_ == null) {
          ensureDailyForecastsIsMutable();
          dailyForecasts_.add(builderForValue.build());
          onChanged();
        } else {
          dailyForecastsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public Builder addDailyForecasts(
          int index, mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder builderForValue) {
        if (dailyForecastsBuilder_ == null) {
          ensureDailyForecastsIsMutable();
          dailyForecasts_.add(index, builderForValue.build());
          onChanged();
        } else {
          dailyForecastsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public Builder addAllDailyForecasts(
          java.lang.Iterable<? extends mwo.psr.proto.WeatherForecastProtos.DailyForecast> values) {
        if (dailyForecastsBuilder_ == null) {
          ensureDailyForecastsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dailyForecasts_);
          onChanged();
        } else {
          dailyForecastsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public Builder clearDailyForecasts() {
        if (dailyForecastsBuilder_ == null) {
          dailyForecasts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dailyForecastsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public Builder removeDailyForecasts(int index) {
        if (dailyForecastsBuilder_ == null) {
          ensureDailyForecastsIsMutable();
          dailyForecasts_.remove(index);
          onChanged();
        } else {
          dailyForecastsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder getDailyForecastsBuilder(
          int index) {
        return getDailyForecastsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder getDailyForecastsOrBuilder(
          int index) {
        if (dailyForecastsBuilder_ == null) {
          return dailyForecasts_.get(index);  } else {
          return dailyForecastsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public java.util.List<? extends mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder> 
           getDailyForecastsOrBuilderList() {
        if (dailyForecastsBuilder_ != null) {
          return dailyForecastsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dailyForecasts_);
        }
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder addDailyForecastsBuilder() {
        return getDailyForecastsFieldBuilder().addBuilder(
            mwo.psr.proto.WeatherForecastProtos.DailyForecast.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder addDailyForecastsBuilder(
          int index) {
        return getDailyForecastsFieldBuilder().addBuilder(
            index, mwo.psr.proto.WeatherForecastProtos.DailyForecast.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.DailyForecast daily_forecasts = 1;</code>
       */
      public java.util.List<mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder> 
           getDailyForecastsBuilderList() {
        return getDailyForecastsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          mwo.psr.proto.WeatherForecastProtos.DailyForecast, mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder, mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder> 
          getDailyForecastsFieldBuilder() {
        if (dailyForecastsBuilder_ == null) {
          dailyForecastsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              mwo.psr.proto.WeatherForecastProtos.DailyForecast, mwo.psr.proto.WeatherForecastProtos.DailyForecast.Builder, mwo.psr.proto.WeatherForecastProtos.DailyForecastOrBuilder>(
                  dailyForecasts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          dailyForecasts_ = null;
        }
        return dailyForecastsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.WeatherForecast)
    }

    // @@protoc_insertion_point(class_scope:tutorial.WeatherForecast)
    private static final mwo.psr.proto.WeatherForecastProtos.WeatherForecast DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mwo.psr.proto.WeatherForecastProtos.WeatherForecast();
    }

    public static mwo.psr.proto.WeatherForecastProtos.WeatherForecast getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WeatherForecast>
        PARSER = new com.google.protobuf.AbstractParser<WeatherForecast>() {
      @java.lang.Override
      public WeatherForecast parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WeatherForecast> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WeatherForecast> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mwo.psr.proto.WeatherForecastProtos.WeatherForecast getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_DailyForecast_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_DailyForecast_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_DailyForecast_CityForecast_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_DailyForecast_CityForecast_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_WeatherForecast_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_WeatherForecast_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026weather_forecast.proto\022\010tutorial\032\037goog" +
      "le/protobuf/timestamp.proto\"\347\001\n\rDailyFor" +
      "ecast\022(\n\004date\030\001 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\022<\n\016city_forecasts\030\002 \003(\0132$.tutori" +
      "al.DailyForecast.CityForecast\032n\n\014CityFor" +
      "ecast\022\021\n\tcity_name\030\001 \001(\t\022\023\n\013temperature\030" +
      "\002 \001(\002\022\020\n\010humidity\030\003 \001(\002\022\022\n\ncloudiness\030\004 " +
      "\001(\002\022\020\n\010pressure\030\005 \001(\002\"C\n\017WeatherForecast" +
      "\0220\n\017daily_forecasts\030\001 \003(\0132\027.tutorial.Dai" +
      "lyForecastB&\n\rmwo.psr.protoB\025WeatherFore" +
      "castProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_tutorial_DailyForecast_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_DailyForecast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_DailyForecast_descriptor,
        new java.lang.String[] { "Date", "CityForecasts", });
    internal_static_tutorial_DailyForecast_CityForecast_descriptor =
      internal_static_tutorial_DailyForecast_descriptor.getNestedTypes().get(0);
    internal_static_tutorial_DailyForecast_CityForecast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_DailyForecast_CityForecast_descriptor,
        new java.lang.String[] { "CityName", "Temperature", "Humidity", "Cloudiness", "Pressure", });
    internal_static_tutorial_WeatherForecast_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_WeatherForecast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_WeatherForecast_descriptor,
        new java.lang.String[] { "DailyForecasts", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
